blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.blog, name='home'),
    path('kategoriler/<slug:slug>/', views.categories_detail, name='category'),
    path('tags/<slug:slug>/', views.tag_detail, name='tag'),
    path('<slug:slug>/', views.detail, name="detail"),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:slug>/', views.detail, name="detail"),
]

sofistik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from home.sitemaps import ServiceSitemap


sitemaps = {
	'services' : ServiceSitemap,

}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml/', sitemap, {'sitemaps':sitemaps}),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", content_type ="text/plain")),
    path('googleb2c85495126fb742.html', TemplateView.as_view(template_name="googleb2c85495126fb742.html")),
    path('samz0cq0ohwg3s88qsh5nv4fc1ysvd.html', TemplateView.as_view(template_name="samz0cq0ohwg3s88qsh5nv4fc1ysvd.html")),
    path('blog/', include('blog.urls')),

    path('', include('home.urls')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

from ckeditor.fields import RichTextField

# Create your models here.

FONTS = (

	("icofont-computer", "bilgisayar"),
	("icofont-chart-bar-graph", "grafik"),
	("icofont-image", "resim"),
	("icofont-settings", "ayar"),
	("icofont-earth", "dünya"),
	("icofont-tasks-alt", "alt görev"),
    ("icofont-award", "ödül"),
    ("icofont-clock-time", "saat"),
    ("icofont-document-folder", "dosya"),
    ("icofont-simple-smile", "gülücük"),
    ("ri-brush-4-line", "mission"),
    ("ri-movie-2-line", "film şeridi"),
    ("ri-calendar-check-line", "takvim"),


)

class Setting(models.Model):
    title = models.CharField("title", max_length=50)
    icon = models.ImageField("İcon", upload_to='setting/')
    logo = models.ImageField("logo", upload_to='setting/',default = "Sofistech")
    description = models.CharField("Google'da çıkacak olan yazı", max_length=150)
    keywords = models.CharField("Google'da aramalarda çıkabilmek için gerekli anahtar kelimler", max_length=150)   
    image = models.ImageField("Ana sayfadaki büyük resim", upload_to='setting/')
    youtube_url = models.URLField("anasayfadaki URL adresi")
    header = models.CharField("ana sayfadaki resim üstündeki başlık", max_length=150, blank=True)
    content = models.CharField("ana sayfadaki resim üsütündeki içerik", max_length=150, blank=True)
    get_startted = models.CharField("Navbardaki get_started", default = "Get Started", max_length=50)
    about = RichTextField()
    facebook_url = models.URLField(blank=True)
    twitter_url = models.URLField(blank=True)
    instagram_url = models.URLField(blank=True)
    skype_url = models.URLField(blank=True)
    linkedin_url = models.URLField(blank=True)
    copyright_name = models.CharField(max_length=50, default="Sofistech")
    adresse = models.CharField(max_length=75)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    whatsapp_phone = models.CharField(max_length=20,default="")
    features = models.BooleanField("Özellikler kısmının gözükmesini istiyorsanız tıklayınız:", default=False)
    testimonials = models.BooleanField("Müşteri yorumlarının sergilenmesi için tıklayınız.", default=False)
    teams = models.BooleanField("Sofistech ekibinin segilenmesi için tıklayınız.", default=False)

    def __str__(self):
        return self.title

class About(models.Model):
    title = models.CharField("hakkımızda başlığı", max_length=150)
    sub_content = models.CharField("hakkımızda alt metin", max_length=250)
    content = RichTextField("içerik")
    about_image = models.ImageField("Hakkımızda kısmında çıkacak olan resim")
    about_youtube_url = models.URLField("Hakkımızda ile ilgili olan youtube URL'i ")

    class Meta:
        #ordering = ('sıralama_sayısı', )
        verbose_name = 'Hakkımızda'
        verbose_name_plural = 'Hakkımızdakiler'

    def __str__(self):
        return self.title

class AboutLogo(models.Model):
    title = models.CharField("açıklama", max_length=50)
    font = models.CharField(max_length=50, choices=FONTS)
    about = models.ForeignKey("About", on_delete =models.CASCADE)
    number = models.IntegerField(default = 0)

    class Meta:
        #ordering = ('sıralama_sayısı', )
        verbose_name = 'Hakkımızdada Bulunan Font'
        verbose_name_plural = 'Hakkımızdada Bulunan Fontlar'

    def __str__(self):
        return self.title


class Mission(models.Model):
    MISSION_FONTS = (
        ("ri-brush-4-line", "mission"),
        ("ri-movie-2-line", "film şeridi"),
        ("ri-calendar-check-line", "takvim"),
    )
    title = models.CharField("Vizyon başlığı", max_length=30)
    content = models.CharField("içerik", max_length=150)
    font = models.CharField(max_length=50, choices=MISSION_FONTS)
    image = models.ImageField("resim")

    class Meta:
        #ordering = ('sıralama_sayısı', )
        verbose_name = 'Vizyon'
        verbose_name_plural = 'Vizyonlar'

    

    def __str__(self):
        return self.title


class Partner(models.Model):
    title = models.CharField("İş ortağının adı:", max_length=50)
    image = models.ImageField()

    class Meta:
        #ordering = ('sıralama_sayısı', )
        verbose_name = 'İş Ortağı'
        verbose_name_plural = 'İş Ortakları'


    def __str__(self):
        return self.title

class Feature(models.Model):

    FEATURE_FONTS = (
        ("ri-gps-line", "gps"),
        ("ri-body-scan-line", "body"),
        ("ri-sun-line", "güneş"),
        ("ri-store-line", "dükkan"),
    )

    font_title = models.CharField("Font Başlık", max_length=50)
    font = models.CharField(max_length=50, choices=FEATURE_FONTS)
    title = models.CharField("Başlık:", max_length=50)
    sub_content = models.CharField("üst içerik", max_length=150)
    content = RichTextField("İçerik")
    image = models.ImageField()
    ranking = models.SmallIntegerField("sıralama", unique=True)

    class Meta:
        #ordering = ('sıralama_sayısı', )
        verbose_name = 'Ekstra Özellikler'
        verbose_name_plural = 'Özellikler'

    def __str__(self):
        return self.title


class Service(models.Model):
    title = models.CharField("Hizmetin adı:", max_length=50, unique=True)
    font = models.CharField(max_length=50, choices=FONTS)
    home_content = models.CharField(max_length=250, default = "Kısa Açıklama")
    content = RichTextField("Servis hakkında bilgi")
    image = models.ImageField()
    slug = models.SlugField(editable = False)
    service_or_not = models.BooleanField("Hizmet ise tıklanacak değilse Tıklanmayacak", default = False)
    software = models.BooleanField("Seo Başlıkları için tıklanacak", default = False)
    description = models.CharField("Google'da çıkacak olan yazı", max_length=150)
    keywords = models.CharField("Google'da aramalarda çıkabilmek için gerekli anahtar kelimler", max_length=150)    
    active = models.BooleanField("Sitede gösterilsin mi", default = False)

    class Meta:
        #ordering = ('sıralama_sayısı', )
        verbose_name = 'Hizmet ve Çözüm'
        verbose_name_plural = 'Hizmet ve Çözümlerimiz'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Service, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('home:detail', kwargs={'slug':self.slug})



class Testimonial(models.Model):
    image = models.ImageField("Müşteri resmi")
    title = models.CharField("Müşteri adı", max_length=50)
    sub_title = models.CharField("Müşteri Ünvanı", max_length=50)
    content = models.CharField("Müşteri Yorumu", max_length=150)

    class Meta:
        #ordering = ('sıralama_sayısı', )
        verbose_name = 'Müşteri Görüşü'
        verbose_name_plural = 'Müşteri Görüşleri'

    def __str__(self):
        return self.title



class CompanyType(models.Model):
    title = models.CharField("Şirket tipi", max_length=10)

    class Meta:
        #ordering = ('sıralama_sayısı', )
        verbose_name = 'Şirket Tipi'
        verbose_name_plural = 'Şirket Tipleri'
    
    def __str__(self):
        return self.title

class Reference(models.Model):
    title = models.CharField("Referansın adı:", max_length=50)
    content = models.CharField("Referansın kısa açıklaması:", max_length=75)
    image = models.ImageField("Referans resmi")
    company_type = models.ForeignKey('CompanyType', on_delete=models.CASCADE)

    class Meta:
        #ordering = ('sıralama_sayısı', )
        verbose_name = 'Referans'
        verbose_name_plural = 'Referanslar'

    def __str__(self):
        return self.title


class Member(models.Model):
    name = models.CharField("isim", max_length=50)
    job = models.CharField("ünvan", max_length=50)
    email = models.EmailField()
    number = models.CharField("Telefon Numarası", max_length=30)
    image = models.ImageField("Profil resmi", blank=True, null=True)
    twitter_url = models.URLField(blank = True)
    facebook_url = models.URLField(blank = True)
    instagram_url = models.URLField(blank = True)
    linkedin_url = models.URLField(blank = True)

    class Meta:
        #ordering = ('sıralama_sayısı', )
        verbose_name = 'Sofistech Üye'
        verbose_name_plural = 'Sofistech Üyeleri'

    def __str__(self):
        return self.name

class Contact(models.Model):
    member = models.ManyToManyField('Member')
    addresse = models.CharField("adres", max_length=150)

    class Meta:
        #ordering = ('sıralama_sayısı', )
        verbose_name = 'İletişim'
        verbose_name_plural = 'İletişim Bilgileri'

    


class ContactInfo(models.Model):
    name = models.CharField("İsminiz:", max_length=40)
    email = models.EmailField("Email:")
    topic = models.CharField("Konu:", max_length = 150)
    content = models.TextField("Mesajınız:")

    class Meta:
        #ordering = ('sıralama_sayısı', )
        verbose_name = 'Gelen Mesaj'
        verbose_name_plural = 'Gelen Mesajlar'

    def __str__(self):
        return self.name

home/forms.py
from django import forms
from .models import ContactInfo

from crispy_forms.helper import FormHelper


class ContactForm(forms.ModelForm):
	class Meta:
		model = ContactInfo
		fields = ('name', 'email', 'topic', 'content',)
		
		
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['name'].widget.attrs['placeholder']= "İsminiz"
		self.fields['name'].widget.attrs['class']= "form-control-sm"
		self.fields['email'].widget.attrs['placeholder']= "Email adresiniz"
		self.fields['email'].widget.attrs['class']= "form-control-sm"
		self.fields['topic'].widget.attrs['class']= "form-control-sm"
		self.fields['topic'].widget.attrs['placeholder']= "Konu"
		self.fields['content'].widget.attrs['class']= "form-control-sm"
		self.fields['content'].widget.attrs['placeholder']= "Mesajınız"
		self.helper = FormHelper()
		self.helper.form_show_labels = False 

blog/views.py
from django.shortcuts import render, get_object_or_404

from .models import Blog, Category, Tag
from home.models import Setting, Service




def blog(request):
    setting  = Setting.objects.first()
    services = Service.objects.filter(service_or_not=True, active = True, software = False)
    solutions = Service.objects.filter(service_or_not=False, active = True, software = False)
    #setting  = Setting.objects.first()

    categories = Category.objects.all()
    blogs = Blog.objects.filter(active= True)
    tags = Tag.objects.all()
    recent_blogs = Blog.objects.all()[0:5]
    
    
    context = {
        "categories": categories,
        "blogs": blogs,
        "recent_blogs": recent_blogs,
        "tags": tags,
        'setting': setting,
        'services': services,
        'solutions': solutions,

    }    
    return render(request, 'blog.html', context)

def detail(request, slug):
    blog = get_object_or_404(Blog, slug = slug, active = True)

    setting  = Setting.objects.first()
    services = Service.objects.filter(service_or_not=True, active = True, software = False)
    solutions = Service.objects.filter(service_or_not=False, active = True, software = False)
    categories = Category.objects.all()

    
    
    context = {
        "blog": blog,
        'categories': categories,
        'setting': setting,
        'services': services,
        'solutions': solutions
    }
    return render(request, 'blog-single.html', context)


def categories_detail(request, slug):
    category = get_object_or_404(Category, slug = slug)

    blogs = Blog.objects.filter(active= True, category= category)
    services = Service.objects.filter(service_or_not=True, active = True, software = False)
    solutions = Service.objects.filter(service_or_not=False, active = True, software = False)
    setting  = Setting.objects.first()
    

    categories = Category.objects.all()
    tags = Tag.objects.all()
    recent_blogs = Blog.objects.all()[0:5]
    
    
    context = {
        "categories": categories,
        "blogs": blogs,
        "recent_blogs": recent_blogs,
        "tags": tags,
        'setting': setting,
        'services': services,
        'solutions': solutions,

    }    

    return render(request, 'blog.html', context)


def tag_detail(request, slug):
    tag = get_object_or_404(Tag, slug = slug)
    blogs = tag.blog_set.all()
    
    services = Service.objects.filter(service_or_not=True, active = True, software = False)
    solutions = Service.objects.filter(service_or_not=False, active = True, software = False)
    setting  = Setting.objects.first()
    

    categories = Category.objects.all()
    tags = Tag.objects.all()
    recent_blogs = Blog.objects.all()[0:5]
    
    context = {
        "categories": categories,
        "blogs": blogs,
        "recent_blogs": recent_blogs,
        "tags": tags,
        'setting': setting,
        'services': services,
        'solutions': solutions,

    }    

    
    return render(request, 'blog.html', context)

    

home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages

from .models import (Setting, Service, Contact, About, Mission, 
Partner, Feature, Testimonial, CompanyType, Reference, Member)
from .forms import ContactForm


# Create your views here.
def home(request):
    setting  = Setting.objects.first()
    services = Service.objects.filter(service_or_not=True, active = True, software = False)
    solutions = Service.objects.filter(service_or_not=False, active = True, software = False)
    softwares = Service.objects.filter(active = True, software = True)
    contact = Contact.objects.first()
    about = About.objects.first()
    missions = Mission.objects.all()
    partners = Partner.objects.all()
    company_types = CompanyType.objects.all()
    references = Reference.objects.all()

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Başarı bir şekilde mesajınız tarafımıza iletilmiştir. En kısa sürede sizinle iletişime geçilecektir.')
            return redirect("/")
    else:
        form = ContactForm()
    

    context = {
        'setting': setting,
        'services': services,
        'solutions': solutions,
        'softwares': softwares,
        'contact': contact,
        'about': about,
        'missions': missions,
        'partners': partners,
        'company_types': company_types,
        'references': references,
        'form': form, 
		
	}
    if setting.features:
        features = Feature.objects.all()
        context["features"] = features
    if setting.testimonials:
        testimonials = Testimonial.objects.all()
        context["testimonials"] = testimonials
    if setting.teams:
        members = Member.objects.all()
        context["members"] = members

    return render(request, 'index.html', context)


def detail(request, slug):
    setting  = Setting.objects.first()
    service = get_object_or_404(Service, slug = slug, active = True)
    # services = Service.objects.filter(service_or_not=True, active = True)
    # solutions = Service.objects.filter(service_or_not=False, active = True)
    # softwares = Service.objects.filter(service_or_not=False, active = True, software = True)
    services = Service.objects.filter(service_or_not=True, active = True, software = False)
    solutions = Service.objects.filter(service_or_not=False, active = True, software = False)
    softwares = Service.objects.filter(active = True, software = True)
    #contact = Contact.objects.first()
    #about = About.objects.first()
    #missions = Mission.objects.all()
    partners = Partner.objects.all()
    

    context = {
        'setting': setting,
        'services': services,
        'solutions': solutions,
        'softwares': softwares,
        #'contact': contact,
        #'about': about,
        #'missions': missions,
        'partners': partners,
        'service': service,
		
	}

    return render(request, 'detail.html', context)

templates/blog-single.html
{% extends 'base.html' %}
{% load static %}



{% block style %}

<link href="{% static 'assets/css/blog/style.css' %}" rel="stylesheet">

{% endblock %}

{% block body %}

{% include 'blog_navbar.html' %}


  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="{% url 'home:home' %}">Home</a></li>
          <li><a href="{% url 'blog:home' %}">Blog</a></li>
          <li>{{blog.title}}</li>
        </ol>
        <h2>{{blog.title}}</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Blog Single Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">

            <article class="entry entry-single">

              <div class="entry-img">
                <img src="{{blog.image.url}}" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="#">{{blog.title}}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="icofont-user"></i> <a href="#">{{blog.user}}</a></li>
                  <li class="d-flex align-items-center"><i class="icofont-wall-clock"></i> <a href="#"><time datetime="2020-01-01">{{blog.publishing_date}}</time></a></li>
                  <!-- <li class="d-flex align-items-center"><i class="icofont-comment"></i> <a href="blog-single.html">12 Comments</a></li> -->
                </ul>
              </div>

              <div class="entry-content">
                <p>{{blog.content|safe}}</p>
              </div>

              <div class="entry-footer clearfix">
                <div class="float-left">
                  <i class="icofont-folder"></i>
                  <ul class="cats">
                    <li><a href="{{blog.category.get_absolute_url}}">{{blog.category.title}}</a></li>
                  </ul>

                  <i class="icofont-tags"></i>
                  <ul class="tags">
                    {% for tag in blog.tags.all %}
                    <li><a href="{{tag.get_absolute_url}}">{{tag.title}}</a></li>
                    {% endfor %}
                  </ul>
                </div>

                <div class="float-right share">
                  <a href="#" title="Share on Twitter"><i class="icofont-twitter"></i></a>
                  <a href="#" title="Share on Facebook"><i class="icofont-facebook"></i></a>
                  <a href="#" title="Share on Instagram"><i class="icofont-instagram"></i></a>
                </div>

              </div>

            </article><!-- End blog entry -->
<!-- 
            <div class="blog-author clearfix">
              <img src="assets/img/blog/blog-author.jpg" class="rounded-circle float-left" alt="">
              <h4>{{blog.user}}</h4>
              <div class="social-links">
                <a href="https://twitters.com/#"><i class="icofont-twitter"></i></a>
                <a href="https://facebook.com/#"><i class="icofont-facebook"></i></a>
                <a href="https://instagram.com/#"><i class="icofont-instagram"></i></a>
              </div>
              <p>
                Itaque quidem optio quia voluptatibus dolorem dolor. Modi eum sed possimus accusantium. Quas repellat voluptatem officia numquam sint aspernatur voluptas. Esse et accusantium ut unde voluptas.
              </p>
            </div> -->
            
            <!-- End blog author bio -->

          
            
            <!-- End blog comments -->

          </div><!-- End blog entries list -->

          <div class="col-lg-4">

            <div class="sidebar">

              <h3 class="sidebar-title">Ara</h3>
              <div class="sidebar-item search-form">
                <form action="">
                  <input type="text">
                  <button type="submit"><i class="icofont-search"></i></button>
                </form>
              </div><!-- End sidebar search formn-->

              <h3 class="sidebar-title">Kategoriler</h3>
              <div class="sidebar-item categories">
                <ul>
                  {% for category in categories %}
                  <li><a href="{{category.get_absolute_url}}">{{category.title}} <span>(25)</span></a></li>
                  {% endfor %}
                </ul>
              </div><!-- End sidebar categories-->

              <h3 class="sidebar-title">İlgili yazılar</h3>
              <div class="sidebar-item recent-posts">
                {% for blog in blog.blogs.all %}
                <div class="post-item clearfix">
                  <img src="{{blog.image.url}}" alt="">
                  <h4><a href="{{blog.get_absolute_url}}">{{blog.title}}</a></h4>
                  <time datetime="2020-01-01">{{blog.publishing_date}}</time>
                </div>
                {% endfor %}
 

              </div><!-- End sidebar recent posts-->

              <h3 class="sidebar-title">Tags</h3>
              <div class="sidebar-item tags">
                <ul>
                  {% for tag in blog.tags.all%}
                  <li><a href="{{tag.get_absolute_url}}">{{tag.title}}</a></li>
                  {% endfor %}
                </ul>
              </div><!-- End sidebar tags-->

            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

          </div><!-- End blog sidebar -->

        </div>

      
    </section><!-- End Blog Single Section -->

  </main><!-- End #main -->

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  {% endblock %}

  {% block main_javascript %}
  <script src="{% static 'assets/js/blog/main.js' %}"></script>
  
  {% endblock %}

templates/blog.html
{% extends 'base.html' %}
{% load static %}



{% block style %}

<link href="{% static 'assets/css/blog/style.css' %}" rel="stylesheet">

{% endblock %}

{% block body %}

{% include 'blog_navbar.html' %}

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="{% url 'home:home' %}">Anasayfa</a></li>
          <li>Blog</li>
        </ol>
        <h2>Blog</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">
            {% for blog in blogs %}
            <article class="entry">

              <div class="entry-img">
                <img src="{{blog.image.url}}" alt="{{blog.title}}" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="{{blog.get_absolute_url}}">{{blog.title}}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="icofont-user"></i> <a href="{{blog.get_absolute_url}}">{{blog.user}}</a></li>
                  <li class="d-flex align-items-center"><i class="icofont-wall-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">{{blog.publishing_date}}</time></a></li>
                  <!-- <li class="d-flex align-items-center"><i class="icofont-comment"></i> <a href="blog-single.html">12 Comments</a></li> -->
                </ul>
              </div>

              <div class="entry-content">
                <p>
                  {{blog.sub_content}}
                </p>
                <div class="read-more">
                  <a href="{{blog.get_absolute_url}}">Devamını okuyunuz...</a>
                </div>
              </div>

            </article><!-- End blog entry -->
            {% endfor %}

            <div class="blog-pagination">
              <ul class="justify-content-center">
                <li class="disabled"><i class="icofont-rounded-left"></i></li>
                <li><a href="#">1</a></li>
                <li class="active"><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#"><i class="icofont-rounded-right"></i></a></li>
              </ul>
            </div>

          </div><!-- End blog entries list -->

          <div class="col-lg-4">

            <div class="sidebar">

              <h3 class="sidebar-title">Ara</h3>
              <div class="sidebar-item search-form">
                <form action="">
                  <input type="text">
                  <button type="submit"><i class="icofont-search"></i></button>
                </form>
              </div><!-- End sidebar search formn-->

              <h3 class="sidebar-title">Kategoriler</h3>
              <div class="sidebar-item categories">
                <ul>
                  {% for category in categories %}
                  <li><a href="{{category.get_absolute_url}}">{{category.title}} <span>(25)</span></a></li>
                  {% endfor %}
                </ul>
              </div><!-- End sidebar categories-->

              <h3 class="sidebar-title">Yeni postlar</h3>
              <div class="sidebar-item recent-posts">
                {% for blog in recent_blogs %}
                <div class="post-item clearfix">
                  <img src="{{blog.image.url}}" alt="">
                  <h4><a href="{{blog.get_absolute_url}}">{{blog.title}}</a></h4>
                  <time datetime="2020-01-01">{{blog.publishing_date}}</time>
                </div>
                {% endfor %}
 

              </div><!-- End sidebar recent posts-->

              <h3 class="sidebar-title">Tags</h3>
              <div class="sidebar-item tags">
                <ul>
                  {% for tag in tags%}
                  <li><a href="{{tag.get_absolute_url}}">{{tag.title}}</a></li>
                  {% endfor %}
                </ul>
              </div><!-- End sidebar tags-->

            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->

	{% endblock %}

  {% block main_javascript %}
  <script src="{% static 'assets/js/blog/main.js' %}"></script>
  
  {% endblock %}



templates/googleb2c85495126fb742.html
google-site-verification: googleb2c85495126fb742.html

templates/navbar.html
{% load static %}
 
 <!-- ======= Header ======= -->
  <header id="header" class="fixed-top ">
    <div class="container-fluid d-flex align-items-center justify-content-between">

      <h1 class="logo">
        <!-- <img src="{% static 'assets/img/sofistech.jpeg' %}"> -->
        <img src="{{setting.logo.url}}">
        <a href="{% url 'home:home' %}">Sofistech</a>
      </h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="{% url 'home:home' %}">Anasayfa</a></li>
          <li class="drop-down"><a href="">Kurumsal</a>
            <ul>
              <li><a href="#about">Hakkımızda</a></li>
              <li class="drop-down"><a href="#clients">İş Ortaklarımız</a>
                <ul>
                 {% for partner in partners %} 
                  <li><a href="#clients">{{partner.title}}</a></li>
                 {% endfor %}
                </ul>
              </li>
            </ul>
          </li>
          <li class="drop-down"><a href="#services">Hizmetlerimiz</a>
            <ul>
             {% for service in services %} 
              <li><a href="{{service.get_absolute_url}}">{{service.title}}</a></li>
             {% endfor %}
            </ul>
          </li>
          <li class="drop-down"><a href="#solutions">Çözümlerimiz</a>
            <ul>
             {% for solution in solutions %} 
              <li><a href="{{solution.get_absolute_url}}">{{solution.title}}</a></li>
             {% endfor %}
            </ul>
          </li>
          


          <li><a href="{% url 'blog:home' %}">Blog</a></li>

          
          <li><a href="#portfolio">Referanslar</a></li>
          <li><a href="#contact">İletişim</a></li>

        </ul>
      </nav><!-- .nav-menu -->

      <!-- <a href="#about" class="get-started-btn scrollto">{{setting.get_startted}}</a> -->

    </div>
  </header><!-- End Header -->

templates/samz0cq0ohwg3s88qsh5nv4fc1ysvd.html
samz0cq0ohwg3s88qsh5nv4fc1ysvd

templates/yapim.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="yandex-verification" content="5e817db5d8305b2e" />
    <title>Document</title>
    <style>
        h1 {
            color: white;
        }
    </style>
</head>
<body style = "background-color: black;" >
    <h1 >Sitemiz yapım aşamasındadır.</h1>
</body>
</html>